// RootLayout.tsx
import * as React from 'react'
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'

import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'
import { Grid, Typography } from '@mui/material'
import AuthProvider from '@/hooks/auth'
import Navbar from '@/components/navbar/navbar'

export const metadata: Metadata = {
  title: 'Expense Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white text-black">
        <ThemeRegistry>
          <AuthProvider>
            <ToastContainer />
            <Navbar/>
            {children}
            <Grid item xs={12} sx={{position: 'fixed', bottom: 20, left: 10}}>
              <Typography variant='caption' sx={{mt: '10px', alignSelf: 'flex-end', mb: '5px'}}>Version 1.0</Typography>
            </Grid>
          </AuthProvider>
          
        </ThemeRegistry>
      </body>
    </html>
  )
}