import * as React from 'react'
import type { Metadata } from 'next'
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'
import { Box } from '@mui/material'

export const metadata: Metadata = {
  title: 'Expense Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const background =
    'linear-gradient(167deg, #A03E3E 1.02%, rgba(0, 0, 0, 0.20) 80.95%)'

  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Box sx={{ flexGrow: 1, background, width: '100%' }}>{children}</Box>
        </ThemeRegistry>
      </body>
    </html>
  )
}
